apiVersion: apps/v1
kind: Deployment
metadata:
  name: jadevlab-deployment
spec:
  selector:
    matchLabels:
      app: jadevlab-app
  replicas: 4
  template:
    metadata:
      labels:
        app: jadevlab-app
    spec:
      containers:
      - name: jadevlab-container
        image: nanajanashia/argocd-app:1.1
        ports:
        - containerPort: 8080
